name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==2.4.0
    - torchvision==0.19.0
    - torchaudio==2.4.0
    - tqdm
    - plyfile